#!/bin/bash

case $(( ${OMPI_COMM_WORLD_LOCAL_RANK} )) in
	0) UCX_NET_DEVICES=mlx5_0:1 CUDA_VISIBLE_DEVICES=0 $* ;;
	1) UCX_NET_DEVICES=mlx5_3:1 CUDA_VISIBLE_DEVICES=1 $* ;;
	2) UCX_NET_DEVICES=mlx5_4:1 CUDA_VISIBLE_DEVICES=2 $* ;;
	3) UCX_NET_DEVICES=mlx5_5:1 CUDA_VISIBLE_DEVICES=3 $* ;;
	4) UCX_NET_DEVICES=mlx5_6:1 CUDA_VISIBLE_DEVICES=4 $* ;;
	5) UCX_NET_DEVICES=mlx5_9:1 CUDA_VISIBLE_DEVICES=5 $* ;;
	6) UCX_NET_DEVICES=mlx5_10:1 CUDA_VISIBLE_DEVICES=6 $* ;;
	7) UCX_NET_DEVICES=mlx5_11:1 CUDA_VISIBLE_DEVICES=7 $* ;;
esac
