#!/bin/sh
#SBATCH -A nti115
#SBATCH -J externalPotential
#SBATCH -t 01:50:00
#SBATCH -p batch
#SBATCH -N 12
#SBATCH --gpus-per-node 8
#SBATCH --ntasks-per-gpu 2
#SBATCH --gpu-bind closest
##SBATCH --dependency=singleton
export OMP_NUM_THREADS=1
export MPICH_VERSION_DISPLAY=1
export MPICH_ENV_DISPLAY=1
export MPICH_OFI_NIC_POLICY=NUMA
export MPICH_GPU_SUPPORT_ENABLED=1
export MPICH_SMP_SINGLE_COPY_MODE=NONE

export FI_MR_CACHE_MONITOR=disabled

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$INST/lib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$INST/lib/lib64
export LD_LIBRARY_PATH=$CRAY_LD_LIBRARY_PATH:$LD_LIBRARY_PATH
export DFTFE_NUM_THREADS=3
export ELPA_DEFAULT_omp_threads=3
export BASE=/lustre/orion/nti115/scratch/kartickr/DFTFE/dftfe_ExternalPotential_Final/buildVis/release/real/
#export BASE=/lustre/orion/nti115/scratch/kartickr/DFTFE/dftfe_PawReimplementation/build/release/real

srun -n $SLURM_NTASKS -c 3 --gpu-bind closest $BASE/dftfe  GS_Sawtooth.prm   > GS_finalCEFM0D002HapBohr.op
